### ISSUE TITLE
Herbstluftwm: I can hide startx messages on login but can't hide xorg errors on shutdown.

### ISSUE THREAD

**Issue by rbilk** [nullgemm/ly#338]
Hi, sorry if this is not the place to post. I just wondered if there is a way I could disable the xorg error messages when shutting down the system?

I checked Arch wiki and https://wiki.archlinux.org/title/Xorg#Session_log_redirection and confirmed that my xorg is running rootless which allegedly means redirection is broken... logs are stored in "~/.local/share/xorg/Xorg.0.log"

I checked past issues:
https://github.com/nullgemm/ly/issues/259
https://github.com/nullgemm/ly/issues/42

both options:
`x_cmd = /usr/bin/X > /dev/null 2>&1`
&
`x_cmd = /usr/bin/X -keeptty > ~/.xorg.log 2>&1`

In the config.ini file work in as much as they silence the startx messages on login. However both options do not seem to affect a bunch of xorg errors showing up on shutdown.

Sorry if this is not an issue with ly, any pointers to solve my problem would be greatly appreciated.

Thanks in advance,

Rob

Edit: I'm using herbstluftwm. I thought using .xinitrc to log in might solve the problem rather than selecting "herbstluftwm" in the session selection - but still seeing error messages on shutdown.

**Comment by rbilk** [comment]
Just figured out I could add "> /dev/null 2>&1" to .xinitrc

`exec herbstluftwm --locked > /dev/null 2>&1` to make shutdown silent.

**Comment by aerofractal** [comment]
Don't mean to dredge up old threads but I'm wondering if anyone has a solution to fix the shutdown messages on exiting your window manager when using the .desktop session file instead of ~/.xinitrc? 
Like in the OP, I have

`x_cmd = /usr/bin/X > /dev/null 2>&1` 

in my `config.ini` which takes care of the start messages, but I still get the X server messages on quitting before `ly` takes the TTY back over
